//
//  MainInteractor.swift
//  BookFinderApp
//
//  Created by 김나희 on 9/1/22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol MainBusinessLogic {
  func doSomething(request: Main.BookData.Request)
}

protocol MainDataStore {
  //var name: String { get set }
}

class MainInteractor: MainBusinessLogic, MainDataStore {
  var presenter: MainPresentationLogic?
  var worker: MainWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: Main.BookData.Request) {
    print(request)
    worker = MainWorker()
    worker?.doSomeWork()
    
    let response = Main.BookData.Response(books: [])
    presenter?.presentSomething(response: response)
  }
}
