//
//  MainModels.swift
//  BookFinderApp
//
//  Created by 김나희 on 9/1/22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum Main {
    enum BookData {
        struct Request {
            let keyword: String?
        }
        struct Response {
            let books: GoogleBookData
        }
        
        struct ViewModelSuccess {
            let displayedBooks: DisplayedBookData
        }
        
        struct ViewModelFailure {
            let errorMessage: String
        }
    }
}

struct DisplayedBookData {
    let totalItemCount: Int
    let books: [Book]?
}

struct Book {
    let title: String
    let authors: [String]
    let description: String
    let thumbnailURL: String
    let infoLink: String
}
