//
//  MainInteractor.swift
//  BookFinderApp
//
//  Created by 김나희 on 9/1/22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol MainBusinessLogic {
    func fetchBookData(request: Main.BookData.Request)
}

protocol MainDataStore {
    //var name: String { get set }
}

final class MainInteractor {
    var presenter: MainPresentationLogic?
    var worker: MainSceneSearchLogic?
}

extension MainInteractor: MainBusinessLogic, MainDataStore {
    // MARK: Do something
    func fetchBookData(request: Main.BookData.Request) {
        let service = SearchAPIProvider()
        worker = MainWorker(service: service)
        worker?.fetchBookData(request: request, completion: { result in
            DispatchQueue.main.async { [weak self] in
                switch result {
                case .success(let data):
                    self?.presenter?.presentData(response: data)
                case .failure(let error):
                    self?.presenter?.presentError(errorMessage: error.localizedDescription)
                }
            }
        })
    }
}

