//
//  MainPresenter.swift
//  BookFinderApp
//
//  Created by 김나희 on 9/1/22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol MainPresentationLogic {
    func presentData(response: Main.BookData.Response)
    func presentError(errorMessage: String)
}

class MainPresenter: MainPresentationLogic {
    
    weak var viewController: MainDisplayLogic?
    
    // MARK: Do something
    
    func presentData(response: Main.BookData.Response) {
        let viewModel = Main.BookData.ViewModelSuccess(displayedBooks: response.books.toDomain())
        viewController?.displayBookData(viewModel: viewModel)
    }
    
    func presentError(errorMessage: String) {
        let viewModel = Main.BookData.ViewModelFailure(errorMessage: errorMessage)
        viewController?.displayError(viewModel: viewModel)
    }
    
}
