//
//  MainWorker.swift
//  BookFinderApp
//
//  Created by 김나희 on 9/1/22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol MainSceneSearchLogic {
    func fetchBookData(request: Main.BookData.Request, completion: @escaping (Result<GoogleBookData, Error>) -> Void)
}

final class MainWorker: MainSceneSearchLogic {
    private let service: SearchSearvice
    
    init(service: SearchSearvice) {
        self.service = service
    }
    
    func fetchBookData(request: Main.BookData.Request, completion: @escaping (Result<GoogleBookData, Error>) -> Void) {
        service.search(keyword: request.keyword, startIndex: request.startIndex) { result in
            switch result {
            case .success(let data):
                completion(.success(data))
            case .failure(let error):
                completion(.failure(error))
            }
            
        }
    }
}
